version: {build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '0.0.4'  
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: ZquxJyH0nVgT5epQq/YQcIkDXQEDo6ze96cC2VanmYc9Kv+9LPfh0LzXvh/lTVfk
  on:
    APPVEYOR_REPO_TAG: true